#pragma once

#define EXAMPLE_DRIVERNAME "QSQLITE"
#define EXAMPLE_HOSTNAME ""
#define EXAMPLE_HOSTPORT 0
#define EXAMPLE_USERNAME ""
#define EXAMPLE_PASSWORD ""
#define EXAMPLE_DATABASE_FILENAME "testDb.sqlite3"
#define EXAMPLE_DATABASE EXAMPLE_DATABASE_FILENAME
