//$Id$
#pragma once

#ifndef POSTGRESQLCONFIG_H
#define POSTGRESQLCONFIG_H

#define POSTGRESQL_DRIVERNAME "QPSQL"

#define POSTGRESQL_HOSTNAME "localhost"
#define POSTGRESQL_HOSTPORT 5432
#define POSTGRESQL_USERNAME "test"
#define POSTGRESQL_PASSWORD "test"

#endif // POSTGRESQLCONFIG_H
